"""Natural Language SQL Agent — LangChain + IBM watsonx Granite + MySQL.

Ask questions about a MySQL database in plain English; a LangChain SQL
agent (ZERO_SHOT_REACT_DESCRIPTION) plans, writes, and executes the SQL,
then answers in natural language.

Based on the IBM Skills Network guided project "Build a Natural Language
SQL Agent" (author: Ricky Shi; contributors: Karan Goswami, Kunal
Makwana, Wojciech "Victor" Fulmyk). Faithful to the lab code with two
changes: database credentials come from environment variables (the lab
hardcoded its temporary lab-database password), and execution sits
behind a __main__ guard for importability.

Usage:
    export MYSQL_PASSWORD="your-password"   # plus optional MYSQL_* vars
    python sql_agent.py --prompt "How many Albums are there?"
"""

# Use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass


import warnings

warnings.warn = warn
warnings.filterwarnings("ignore")

import argparse  # noqa: E402

from ibm_watsonx_ai.foundation_models import ModelInference  # noqa: E402
from ibm_watsonx_ai.metanames import (  # noqa: E402
    GenTextParamsMetaNames as GenParams,
)
from ibm_watson_machine_learning.foundation_models.extensions.langchain import (  # noqa: E402,E501
    WatsonxLLM,
)
from langchain.agents import AgentType  # noqa: E402
from langchain_community.agent_toolkits import create_sql_agent  # noqa: E402
from langchain_community.utilities.sql_database import SQLDatabase  # noqa: E402

from db_config import get_mysql_uri_from_env  # noqa: E402

MODEL_ID = "ibm/granite-4-h-small"

PARAMETERS = {
    GenParams.MAX_NEW_TOKENS: 1024,
    GenParams.TEMPERATURE: 0.2,
    GenParams.TOP_P: 0.95,
    GenParams.REPETITION_PENALTY: 1.2,
}

CREDENTIALS = {"url": "https://us-south.ml.cloud.ibm.com"}

# Works only inside IBM Skills Network; use your own project_id elsewhere
PROJECT_ID = "skills-network"


def build_agent():
    """Assemble the watsonx LLM, SQLDatabase, and LangChain SQL agent."""
    model = ModelInference(
        model_id=MODEL_ID,
        params=PARAMETERS,
        credentials=CREDENTIALS,
        project_id=PROJECT_ID,
    )
    llm = WatsonxLLM(model=model)

    db = SQLDatabase.from_uri(get_mysql_uri_from_env())

    return create_sql_agent(
        llm=llm,
        db=db,
        verbose=True,
        handle_parsing_errors=True,
        agent_type=AgentType.ZERO_SHOT_REACT_DESCRIPTION,
    )


def parse_args(argv=None):
    """Parse the --prompt command-line argument."""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--prompt", type=str, help="The prompt to send to the SQL agent"
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = parse_args()
    if args.prompt:
        agent_executor = build_agent()
        agent_executor.invoke(args.prompt)
    else:
        print("Please provide a prompt using --prompt argument")
